name: medico
description: All purpose medical app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_feather_icons: ^2.0.0
  salomon_bottom_bar: ^3.0.0
  gender_picker: ^1.0.2
  enum_to_string: ^2.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.20.0-nullsafety
  flutter_swiper: ^1.1.6
  readmore: ^2.0.0
  pattern_formatter: ^2.0.0
  http: ^0.13.3
  firebase_storage: ^8.1.3
  image_picker: ^0.8.0+3
  permission_handler: ^8.1.0
  auto_size_text_pk: ^3.0.0
  flutter_rating_bar: ^4.0.0
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  path_provider: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/
     - images/feather/
     - images/Doctor_types/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

    - family: RobotoReg
      fonts:
            - asset: fonts/Montserrat-SemiBold.ttf

    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Poiret
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Coda
      fonts :
        - asset : fonts/Coda-Regular.ttf
    - family: Muli
      fonts:
        - asset: fonts/muli/Muli.ttf
        - asset: fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: fonts/muli/Muli-Light.ttf
          weight: 300
