name: medico
description: All purpose medical app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_feather_icons: ^2.0.0
  salomon_bottom_bar: ^3.0.0
  gender_picker: ^1.0.2
  enum_to_string: ^2.0.1
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

    - family: RobotoReg
      fonts:
            - asset: fonts/Montserrat-SemiBold.ttf

    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Poiret
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Coda
      fonts :
        - asset : fonts/Coda-Regular.ttf
